server:
  port: 8801
spring: 
  redis:
    database: 0
    host: 39.108.124.91
    port: 8067
    password: Jhf&*d93jfdKJSf
    pool:
      max-active: 400
      max-wait: 10000
      max-idle: 100
      min-idle: 0
    timeout: 0
