server:
  port: 8901
spring: 
  redis: 
    timeout: 0
    database: 0
    host: 192.168.2.13
    port: 8811
    password: Jhf&*d93jfdKJSf
    pool: 
      max-active: 200
      max-wait: 10000
      max-idle: 8
      min-idle: 0